### ISSUE TITLE
Sort Breaks with mixed data

### ISSUE THREAD

**Issue by ebini** [jstable/JSTable#17]
Hi,

i really appreciate your javascript.

i have a table with a column which has numbers and - the String "N/A" if i got no data.
The sorting seems to "break":

```
<!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" type="text/css" href="./dist/jstable.css">
    <script type="text/javascript" src="./dist/jstable.min.js"></script>
    <script type="text/javascript" src="./dist/jstable.es5.min.js"></script>
    <script type="text/javascript" src="./dist/polyfill-fetch.min.js"></script>
</head>

<body>
    <table id="myTable">
        <thead>
            <tr class="header">
                <th>Test</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>0</td>
            </tr>
            <tr>
                <td>15</td>
            </tr>
            <tr>
                <td>N/A</td>
            </tr>
            <tr>
                <td>0</td>
            </tr>
            <tr>
                <td>7</td>
            </tr>
            <tr>
                <td>33</td>
            </tr>
            <tr>
                <td>N/A</td>
            </tr>
            <tr>
                <td>2</td>
            </tr>
            <tr>
                <td>0</td>
            </tr>
        </tbody>
    </table>
    <script>
        let myTable = new JSTable("#myTable");
    </script>
</body>

</html>
```

so it starts sorting, until it seems to hit a "N/A" and then start again sorting.

can this be fixed (or have i used this js wrong?)

Thanks

Best regards

**Comment by Trekky12** [comment]
Hey @ebini, 

thank you for your feedback.
So first you don't need to include both javascript files `jstable.min.js` and `jstable.es5.min.js`. Only one file is needed. If you support current browsers you can just use the `jstable.min.js`. The file `jstable.es5.min.js` is only needed for compatibility with browsers that don't support current ES6 features.

I checked your example (and everything is used correct) and apparently there is indeed a problem with mixed data in some browsers, Chrome for example is working fine but Firefox has the issue which you described.
I will try to fix this as soon as possible.

Best regards

**Comment by Trekky12** [comment]
@ebini Could you please try the new version 1.5.1?

**Comment by ebini** [comment]
Thanks it is working now!
I'm very thankful!
