### ISSUE TITLE
Server Response Auto load

### ISSUE THREAD

**Issue by Fzoltan87** [jstable/JSTable#21]
Hy,

After loading the page, my spreadsheet is empty, but when I perform an operation (scrolling, searching) I get a server response.
How can I make the server response run automatically after the page loads?
Maybe an idea? Or a sample code?

My source code and structure:

**datalist.php =>Data from the database**

**"deferLoading"** Is this parameter required?

index.php
----------
```
<table id="recordlist" width="100%">
<thead>
<tr>
<th>Name</th>
<th>Status</th>
<th style="width:10%;">Modify</th>
<th style="width:10%;">Delete</th>
</tr>
</thead>
<tbody></tbody>
</table>


let table = new JSTable("#recordlist", {
	serverSide : true,
	addQueryParams: false,
	deferLoading: 5,
	ajax : "datalist.php"
});
```

**Comment by Trekky12** [comment]
Yes, this is correct, the first rendering needs to be done when creating the table.

**Comment by Fzoltan87** [comment]
Very good. Thank you very much. Are you planning any new features or fixes in the script in the future?

**Comment by Trekky12** [comment]
Actually there is currently nothing specific planned. Do you have a feature request?

**Comment by Fzoltan87** [comment]
I would be interested for the server to respond automatically after the page loads (html and javascript code should be php free).

**Comment by Fzoltan87** [comment]
Great. Thank you ;)

**Comment by Fzoltan87** [comment]
Hy Trekky12! Did you manage to look it up?

**Comment by Trekky12** [comment]
Could you please test the version in the development branch? When the option `deferLoading` is not set the table should be loaded from the server.

**Comment by Fzoltan87** [comment]
Success. The server data is downloaded without entering the php code (In Javascript code without specifying a deferLoading value).

**Comment by Trekky12** [comment]
Great! I've published the changes in the new version.
This update is free ;-) You can of course buy me a coffee if you like at https://www.buymeacoffee.com/YXln3gCkm

**Comment by Fzoltan87** [comment]
> Great! I've published the changes in the new version. This update is free ;-) You can of course buy me a coffee if you like at https://www.buymeacoffee.com/YXln3gCkm

Thank you very much for your help. I invited you to coffee. :)

**Comment by Trekky12** [comment]
Great! Thank you! ☺️
