### ISSUE TITLE
Select All Checkbox

### ISSUE THREAD

**Issue by Fzoltan87** [jstable/JSTable#22]
Hy.

How can the selection of checkboxes for all rows be solved if the data comes from the server side?

HTML code (Select All Chekcbox):
```
<label class="toggle-switchy" for="allRowsSelect" data-size="lg" data-color="green">
<input id="allRowsSelect" class="selectAll" type="checkbox">
<span class="toggle"><span class="switch"></span></span>
</label>
```

Checkbox returned from the Server side (These values would be needed)
```
<label class="toggle-switchy" for="fdc4" data-size="lg" data-color="green"
<input type="checkbox" id="fdc4" value="4" class="form-del-chx" name="ch[]">
<span class="toggle"><span class="switch"></span></span>
</label>
```

JS code:
```
let table = new JSTable("#record", {
	serverSide : true,
	addQueryParams: false,
	ajax : "datalist.php"
});

let checkBoxes = document.querySelectorAll('.form-del-chx');

let selectAll = document.querySelector('.selectAll');

selectAll.addEventListener('click', SelectAllCHX);

function SelectAllCHX() {
	checkBoxes.forEach(item => {
		if(item.checked == false) {
			item.checked = true;
		} else {
			item.checked = false;
		}
	})
}
```

**Comment by Trekky12** [comment]
Dynamic created elements are not available when the DOM is created and so it isn't available for eventlisteners.
You can attach the eventlistener to the parent object and check for the clicked child. Yl
You can find an example here: https://elliotekj.com/posts/2016/11/05/jquery-to-pure-js-event-listeners-on-dynamically-created-elements/

**Comment by Fzoltan87** [comment]
> Dynamic created elements are not available when the DOM is created and so it isn't available for eventlisteners. You can attach the eventlistener to the parent object and check for the clicked child.
> 
> You can find an example here: https://elliotekj.com/posts/2016/11/05/jquery-to-pure-js-event-listeners-on-dynamically-created-elements/
> 
> You can for example use the following snippet:
> 
> ```
> document.addEventListener('click', function (event) {
>     let checkAllRowsInput = event.target.closest('#checkAllRows');
>     if (checkAllRowsInput) {
>         let checkboxes = document.querySelectorAll('#table tbody input[type="checkbox"]');
>         checkboxes.forEach(function (checkbox) {
>             if (checkAllRowsInput.checked) {
>                 checkbox.checked = true;
>             } else {
>                 checkbox.checked = false;
>             }
>         });
>     }
> });
> ```

It works, thanks. ;)
