### ISSUE TITLE
method

### ISSUE THREAD

**Issue by merdj** [jstable/JSTable#25]
Hi,

How can I use POST instead of GET?

thanks

**Comment by Trekky12** [comment]
Hey @merdj, 

POST is currently not supported. Feel free to submit a pull request for an option to specify the method (https://github.com/jstable/JSTable/blob/master/src/jstable.js#L341).

**Comment by bungambohlah** [comment]
hi there, i can solve this issue, but it's need label it for hacktoberfest, is that okay? @Trekky12
