### ISSUE TITLE
Search delay

### ISSUE THREAD

**Issue by Sorc96** [jstable/JSTable#27]
Especially for server side processing, sending a request after every keypress can be problematic. Not only does it give the server more work to do, but if an earlier request takes longer to finish, the correct result gets replaced with the earlier one.

An option for delay between requests would be useful. Also, only sending the request if the query changed could be a nice improvement. I can make a PR if needed.

**Comment by Trekky12** [comment]
Thank you for your comment. I support an option for a search delay.
It would be great when you make a pull request for this feature.
