### ISSUE TITLE
Bootstrap 5 Tooltip doesn't work on columns of JSTable

### ISSUE THREAD

**Issue by Fzoltan87** [jstable/JSTable#32]
How can I make the [BS 5 Tooltip](https://getbootstrap.com/docs/5.2/components/tooltips/) work on table columns?

**Comment by Trekky12** [comment]
Could you please provide some example code?

**Comment by Fzoltan87** [comment]
Yes. [Here is the link.](https://www.sda.zwp.hu/)

Edit button added for tooltip parameters (<button type="button" class="btn btn-warning btn-sm" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="Tooltip on top">Edit</button>)

The tooltip code in the html source code:
```
const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]');
const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl));
```

**Comment by Trekky12** [comment]
The HTML table is created dynamically so you can't access the elements directly. 
You could for example add an event listener for the `update` event like this:
```
table.on("update", function () {
    const tooltipTriggerList = document.querySelectorAll('#customer_table button[data-bs-toggle="tooltip"]');
    const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl));
    console.log(tooltipList);
});
```

Please note that the `>` operator in the CSS is not working (don't know exactly why at the moment).

**Comment by Fzoltan87** [comment]
Hey! Thanks, the solution works.

This is how it works with the css **>** operator:
```
table.on("update", function () {
	const tooltipTriggerList = document.querySelectorAll('#customer_table > tbody > tr > td > button[data-bs-toggle="tooltip"]');
	const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl));
});
```

**Comment by Trekky12** [comment]
Great! When you want to enable tooltips for all elements on the page [data-bs-toggle="tooltip"] should be enough.
