### ISSUE TITLE
change values  in ajaxParams when calling update()

### ISSUE THREAD

**Issue by yabdab** [jstable/JSTable#37]
When I create the table using ajaxParams everything works great.

The problem is, I want to change the ajaxParams and update the table. The initial values never change.

Is there a way to do this without having to tear down and rebuild the table?

**Comment by Trekky12** [comment]
I think it should be possible to change the value of `jstable.config.ajaxParams` after the initialization.
The fetch request is always using the latest version of the config (see https://github.com/jstable/JSTable/blob/433e156cdaf42cd09bd76f93a37766cc39b0648d/src/jstable.js#L342)

**Comment by yabdab** [comment]
Excellent! Exactly what I needed. Thanks so much friend.
